---
title: "Network"
author: "MD"
date: "'r format(Sys.time(), '%b %d, %Y')'"
output: 
 html_document:
   toc: true
   toc_float: true
   editor_options:
     chunk_output_type: console
   chunck_output_type: console
   chunk_output_type: console
---

install packages load libraries and load data
```{r}
library(chorddiag)
library(file2meco)  
library(microeco) 
library(igraph)
library(rgexf)
library(RColorBrewer)
library(phyloseq)
```


```{r}
P.count <- readRDS('data/P.count.RDS')  %>% 
   subset_samples(., final >= 10000)


rank <- 'species'
P.glom <- tax_glom(P.count, taxrank=rank)
tax_table(P.glom) <- tax_table(P.glom)[,1:7]
taxa_names(P.glom) <- tax_table(P.glom)[,'species']

dataset <- phyloseq2meco(P.glom)
dataset

dataset$tidy_dataset()
dataset$sample_sums() %>% range
dataset$cal_abund()
dataset$save_abund(dirpath = "taxa_abund")
```


```{r}
#subset to include data for each domestication group
unfert <- clone(dataset)
unfert$sample_table <- subset(unfert$sample_table, Fertilization == "Unfertilized")
unfert$tidy_dataset()
unfert
fert <- clone(dataset)
fert$sample_table <- subset(fert$sample_table, Fertilization == "Fertilized")
fert$tidy_dataset()
fert
MF <- clone(dataset)
MF$sample_table <- subset(MF$sample_table, Domestication == "Modern" & Fertilization == 'Fertilized')
MF$tidy_dataset()
MF
MU <- clone(dataset)
MU$sample_table <- subset(MU$sample_table, Domestication == "Modern" & Fertilization =='Unfertilized')
MU$tidy_dataset()
MU
TF <- clone(dataset)
TF$sample_table <- subset(TF$sample_table, Domestication == "Traditional" & Fertilization == 'Fertilized')
TF$tidy_dataset()
TF
TU <- clone(dataset)
TU$sample_table <- subset(TU$sample_table, Domestication == "Traditional" & Fertilization =='Unfertilized')
TU$tidy_dataset()
TU
WF <- clone(dataset)
WF$sample_table <- subset(WF$sample_table, Domestication == "Wild" & Fertilization == 'Fertilized')
WF$tidy_dataset()
WF
WU <- clone(dataset)
WU$sample_table <- subset(WU$sample_table, Domestication == "Wild" & Fertilization =='Unfertilized')
WU$tidy_dataset()
WU
```



Generate network for whole dataset
```{r}
n <- trans_network$new(dataset = unfert, cor_method = "spearman", filter_thres = 0.001)
n$cal_network(COR_p_thres = 0.01, COR_p_adjust = "fdr", COR_optimization = TRUE)
n$cal_sum_links(taxa_level = "phylum")
n$cal_module(method = "cluster_fast_greedy")
n$save_network(filepath = "data/network_tests/061424-WholeNetworkUnfert.gexf")
```


```{r}
nf <- trans_network$new(dataset = fert, cor_method = "spearman", filter_thres = 0.001)
nf$cal_network(COR_p_thres = 0.01, COR_p_adjust = "fdr", COR_optimization = TRUE)
nf$cal_sum_links(taxa_level = "phylum")
nf$cal_module(method = "cluster_fast_greedy")
nf$save_network(filepath = "data/network_tests/071824-WholeNetworkFert.gexf")
```



```{r}
n.WU <- trans_network$new(dataset = WU, cor_method = "spearman", filter_thres = 0.001)
n.WU$cal_network(COR_p_thres = 0.01, COR_optimization = TRUE)
n.WU$cal_module(method = "cluster_fast_greedy")
n.WU$save_network(filepath = "data/network_tests/071824-WILDU.gexf")


n.TU <- trans_network$new(dataset = TU, cor_method = "spearman", filter_thres = 0.001)
n.TU$cal_network(COR_p_thres = 0.01, COR_p_adjust = "fdr", COR_optimization = TRUE)
n.TU$cal_module(method = "cluster_fast_greedy")
n.TU$save_network(filepath = "data/network_tests/071824-TRADU.gexf")

n.MU <- trans_network$new(dataset = MU, cor_method = "spearman", filter_thres = 0.001)
n.MU$cal_network(COR_p_thres = 0.01, COR_p_adjust = "fdr", COR_optimization = TRUE)
n.MU$cal_module(method = "cluster_fast_greedy")
n.MU$save_network(filepath = "data/network_tests/071824-MODERNU.gexf")

n.WF <- trans_network$new(dataset = WF, cor_method = "spearman", filter_thres = 0.001)
n.WF$cal_network(COR_p_thres = 0.01, COR_optimization = TRUE)
n.WF$cal_module(method = "cluster_fast_greedy")
n.WF$save_network(filepath = "data/network_tests/071824-WILDF.gexf")


n.TF <- trans_network$new(dataset = TF, cor_method = "spearman", filter_thres = 0.001)
n.TF$cal_network(COR_p_thres = 0.01, COR_p_adjust = "fdr", COR_optimization = TRUE)
n.TF$cal_module(method = "cluster_fast_greedy")
n.TF$save_network(filepath = "data/network_tests/071824-TRADF.gexf")

n.M <- trans_network$new(dataset = MF, cor_method = "spearman", filter_thres = 0.001)
n.M$cal_network(COR_p_thres = 0.01, COR_p_adjust = "fdr", COR_optimization = TRUE)
n.M$cal_module(method = "cluster_fast_greedy")
n.M$save_network(filepath = "data/network_tests/071824-MODERNF.gexf")
```


```{r}
W <- clone(dataset)
W$sample_table <- subset(W$sample_table, Domestication == "Wild" )
W$tidy_dataset()
W
nW <- trans_network$new(dataset = W, cor_method = "spearman", filter_thres = 0.001)
nW$cal_network(COR_p_thres = 0.01, COR_p_adjust = "fdr", COR_optimization = TRUE)
nW$cal_module(method = "cluster_fast_greedy")
nW$save_network(filepath = "data/network_tests/071824-WILD.gexf")

t <- clone(dataset)
t$sample_table <- subset(t$sample_table, Domestication == "Traditional" )
t$tidy_dataset()
t
nt <- trans_network$new(dataset = t, cor_method = "spearman", filter_thres = 0.001)
nt$cal_network(COR_p_thres = 0.01, COR_p_adjust = "fdr", COR_optimization = TRUE)
nt$cal_module(method = "cluster_fast_greedy")
nt$save_network(filepath = "data/network_tests/071824-TRAD.gexf")

m <- clone(dataset)
m$sample_table <- subset(m$sample_table, Domestication == "Modern" )
m$tidy_dataset()
m
nm <- trans_network$new(dataset = m, cor_method = "spearman", filter_thres = 0.001)
nm$cal_network(COR_p_thres = 0.01, COR_p_adjust = "fdr", COR_optimization = TRUE)
nm$cal_module(method = "cluster_fast_greedy")
nm$save_network(filepath = "data/network_tests/071824-MOD.gexf")
```



Generate chord diagrams 
```{r}
n$cal_sum_links(taxa_level = "phylum")
n$plot_sum_links(plot_pos = TRUE, plot_num = 10, color_values  = c('#CE2020', '#660066','#bcefff','#E87A4E','#CE20C8','#7720CE','#202CCE','#20CE20','#20B7CE','#20CE89'))

nf$cal_sum_links(taxa_level = "phylum")
nf$plot_sum_links(plot_pos = TRUE, plot_num = 10, color_values  = c('#CE2020', '#660066','#E87A4E','#bcefff','#CE20C8','#7720CE','#202CCE','#00DFDA','#20CE20','#20B7CE'))

```


